CREATE DATABASE Ecole;
USE Ecole;
CREATE TABLE IF NOT EXISTS etudiants
(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Nom VARCHAR(150),
Prenom VARCHAR(150),
Date VARCHAR(50)
);

ALTER TABLE etudiants
ADD NumClass int;