
services:
  # service BDD mysql
  db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=demo_spring_data
    volumes:
      - ex9_volume:/var/lib/mysql
      
    networks:
      - sql_network

  # service phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - sql_network

  programm1:
     build: .
     restart: always
     container_name: personne_container 
     ports:
      - "8080:8080"
     depends_on:
      - db
     networks:
      - sql_network

  programm2:
     build: .
     restart: always
     container_name: adresse_container 
     ports:
      - "8090:8080"
     depends_on:
      - db
     networks:
      - sql_network

volumes:
  ex9_volume:

networks:
  sql_network: